baseURL: "https://andrewgillock.netlify.app/"
languageCode: "en-us"
title: "Andrew's Personal Website"
theme: "hugo-profile"

Paginate: 3
disqusShortname: gurusabarish
googleAnalytics: G-DWJJVE27WD

markup:
  goldmark:
    renderer:
      unsafe: true

# Menus:
#   main:
#     - identifier: blog
#       name: Blog
#       title: Blog posts
#       url: /blogs
#       weight: 1
# 
#     #Dropdown menu
#     - identifier: dropdown
#       title: Example dropdown menu
#       name: Resources
#       weight: 2
#     - identifier: dropdown1
#       title: example dropdown 1
#       name: example 1
#       url: /#
#       parent: dropdown
#       weight: 1
#     - identifier: dropdown2
#       title: example dropdown 2
#       name: example 2
#       url: /#
#       parent: dropdown
#       weight: 2

params:
  title: ""
  description: Text about my cool site
  # staticPath: ""  # The path to serve the static files from
  favicon: "/favicon.ico"

  theme:
    disableThemeToggle: false
    # defaultTheme: "light" # dark

  # font:
  #   fontSize: 1.5rem # default: 1rem
  #   fontWeight: 500 # default: 400
  #   lineHeight: 1 # default: 1.5
  #   textAlign: right # default: left

  # color preference
  # color:
  #   textColor:
  #   secondaryTextColor:
  #   backgroundColor:
  #   secondaryBackgroundColor:
  #   primaryColor:
  #   secondaryColor:

  #   darkmode:
  #     textColor:
  #     secondaryTextColor:
  #     backgroundColor:
  #     secondaryBackgroundColor:
  #     primaryColor:
  #     secondaryColor:

  # If you want to customize the menu, you can change it here
  # navbar:
  #   align: mx-auto # Left: ms-auto | center: mx-auto | right: me-auto | Default: ms-auto
  #   brandLogo: "/logo.png" # Logo for the brand | default is the favicon variable
  #   brandName: "Profile" # Brand name for the brand | default is the title variable

  #   menus:
  #     disableAbout: true
  #     disableExperience: true
  #     disableEducation: true
  #     disableProjects: true
  #     disableAchievements: true
  #     disableContact: true

  # Hero
  hero:
    enable: true
    intro: "Hi there! My name is"
    title: "Andrew Gillock"
    subtitle: "I'm a Business Analytics graduate student at the McCombs School of Business"
    #content: "test..."
    image: /images/me2.png
    button:
      enable: true
      name: "Resume"
      #url: "/testresume.pdf"
      url: /personalResume.pdf
    socialLinks:
      fontAwesomeIcons:
        - icon: fab fa-github
          url: https://github.com/andrewgillock
        - icon: fab fa-linkedin
          url: https://linkedin.com/in/andrewgillock
      # customIcons:
      #   - icon: /fav.png
      #     url: "https://example.com"

  # About
  about:
    enable: true
    title: "About Me"
    image: /images/me.jpg
    content: |-
      I was born and raised in San Antonio, Texas. 
      I enjoy spending my free time outside whether it's paddleboarding, hiking, tennis, basketball, or just going for a walk. 
      My favorite sports teams are the San Antonio Spurs and the Texas Longhorns! 
      I'll listen to most types of music, but country, jazz, and hip-hop are some of my favorites. I'm always welcome to new recommendations as well.
      
      I've been fortunate to attend the University of Texas at Austin for both undergrad and graduate school.
      Studying biology during my time as an undergraduate student introduced me to data analysis, which I realized is relevant and applicable in nearly every field of work.
      Obtaining my Applied Statistical Modeling certificate provided me with first experiences in statistical methods and programming. 
      I decided to pursue graduate studies in this field because I've felt drawn to the capabilities of data-driven solutions.
      
      I hope to use data to make informed decisions about the future and reduce the error and risk accompanied by change.
      With the amount of data generated in our day-to-day lives, we have the potential to solve global contemporary issues using minimal resources and time. 
      Although I am still learning, I have come to enjoy the process of wrangling/cleaning datasets, building predictive models, and visualizing the results.
      
      
    skills:
      enable: true
      title: "Here are some skills of mine:"
      items:
        - "R: dplyr, machine learning/predictive models, data visualization"
        - "Python: Pandas, Scikit-Learn"
       
        
        

  # Experience
  # experience:
  #   enable: true
  #   items:
  #     - job: "Senior Software Developer"
  #       company: "Facebook"
  #       companyUrl: "https://example.com"
  #       date: "Jan 2022 - present"
  #       featuredLink:
  #         enable: true
  #         name: "View the project"
  #         url: "https://example.com"
  #       content: "I am currently working as a software developer at [example org.](https://example.com) in San Francisco, CA. I am currently working on a project that will be used to help people find the best way to get around the city."
  # 
  #     - job: "Software Developer"
  #       company: "Amazon"
  #       companyUrl: "https://example.com"
  #       date: "Sep 2020 - Dec 2021"
  #       featuredLink:
  #         enable: true
  #         url: "https://example.com"
  #       info:
  #         enable: true
  #         content: I worked as a software developer for more than one year in Amazon.
  #       content: |
  #         I am currently working as a software developer at [example org.](https://example.com) in San Francisco, CA. I am currently working on a project that will be used to help people find the best way to get around the city.
  # 
  #         - Lead backend developer for a product.
  #         - Created a frontend design for a product.
  # 
  #     - job: "Junior Software Developer"
  #       company: "Apple"
  #       companyUrl: "https://example.com"
  #       date: "Jan 2020 - Aug 2020"
  #       info:
  #         enable: false
  #       featuredLink:
  #         enable: true
  #         url: "https://example.com"
  #       content: |
  #         I am currently working as a software developer at [example org.](https://example.com) in San Francisco, CA. I am currently working on a project that will be used to help people find the best way to get around the city.
  # 
  #         - Lead backend developer for a product.
  #         - Created a frontend design for a product.
  # 
  #     - job: "UI/UX Designer"
  #       company: "Netflix"
  #       companyUrl: "https://example.com"
  #       date: "June 2017 - Nov 2019"
  #       featuredLink:
  #         enable: true
  #         url: "https://example.com"
  #       content: |
  #         I am currently working as a software developer at [example org.](https://example.com) in San Francisco, CA. I am currently working on a project that will be used to help people find the best way to get around the city.
  # 
  #         - Lead backend developer for a product.
  #         - Created a frontend design for a product.
  # 
  #     - job: "Product Designer"
  #       company: "Google"
  #       companyUrl: "https://example.com"
  #       date: "Feb 2016 - Mar 2017"
  #       content: "I am currently working as a software developer at [example org.](https://example.com) in San Francisco, CA. I am currently working on a project that will be used to help people find the best way to get around the city."

  # Education
  education:
    enable: true
    #index: true
    items:
      - title: "Master of Science in Business Analytics"
        school:
          name: "The University of Texas at Austin - McCombs School of Business"
          url: "https://www.mccombs.utexas.edu/graduate/ms-programs/ms-business-analytics/"
        date: "July 2022 - May 2023"
        #GPA: "3.8 out of 5.0"
        content: |-
            
        
        featuredLink:
          enable: true
          name: "Coursework"
          url: "https://www.mccombs.utexas.edu/graduate/ms-programs/ms-business-analytics/academics/curriculum/#d.en.19643"
          
            
      - title: "Bachelor of Science and Arts in Biology"
        school:
          name: " The University of Texas at Austin - College of Natural Sciences"
          url: "https://www.cns.utexas.edu/"
        date: "August 2018 - May 2022"
        #GPA: "3.64 / 4.0"
        content: |-
              Minor: Business
              
              Certificates: Applied Statistical Modeling, Pre-Health Professions

        
  # Achievements
  achievements:
    enable: false
    items:
      # - title: Google kickstart runner
      #   content: I solved all problems with optimal solution.
      #   url: https://example.com
      # - title: Facebook Hackathon Winner
      #   content: Developed a product using Artificial Intelligence.
      # - title: Hugo Profile
      #   content: Developed a theme and getting 1K+ downloads per month.
      #   url: "https://github.com/gurusabarish/hugo-profile"
      # - title: Microsoft Imagine Runner
      #   content: We are developed a product which can help others.
      # - title: Google Summer of Code
      #   content: Contributed to a open source project.
      #   url: https://example.com

  # projects
  projects:
    enable: true
    items:
      - title: Designing Ideal Classification Models for Malignant and Benign Breast Tumor Samples
        content: Classification investigation using tree-based methods, Spring 2022
        image: /images/sds323Final.png
        featured:
          name: PDF
          link: /sds323final.pdf
        badges:
          - "R"
          - "Classification"
        
        # links: #adds icons and links to bottom of project
        #   - icon: fa fa-envelope
        #     url: mailto:?subject=Hugo%20Profile%20Template&body=Check%20it%20out:%20https%3a%2f%2fhugo-profile.netlify.app%2fblog%2fmarkdown-syntax%2f
        #   - icon: fab fa-github
        #     url: https://github.com/gurusabarish/hugo-profile
        #   - icon: fab fa-twitter
        #     url: https://twitter.com/intent/tweet?text=Check+it+out:&url=https%3A%2F%2Fgithub.com%2Fgurusabarish%2Fhugo-profile

      - title: 'Exploratory Analysis: Collegiate Sports Revenue' #in quotes because of ':''
        content: Regressional analysis of revenue by sport, Spring 2022
        image: /images/sds375.png
        featured:
          name: PDF
          link: /sds375.pdf
        badges:
          - "R"
          - "Regression"
          - "Data Visualization"
        # links:
        #   - icon: fab fa-github
        #     url: https://github.com/gurusabarish/converter

      - title: 'Exploratory Analysis: Website Ratings'
        content: Data exploration using Pandas library, Summer 2022
        image: /images/hw3.png
        featured:
          name: PDF
          link: /hw3.pdf
        badges:
          - "Pandas"
          - "Data Analysis"
        # links:
        #   - icon: fab fa-github
        #     url: https://github.com/gurusabarish/converter


      - title: Document Analysis & Association Rule Mining 
        content: Using TF-IDF to classify documents and network analysis of customer grocery baskets, Summer 2022
        image: /images/STA380.png
        featured:
          name: PDF
          link: /STA380.pdf
        badges:
          - "R"
          - "Bag of Words"
          - "Networks"
        links:
          - icon: fab fa-github
            url: https://github.com/andrewgillock/groupExercises

  #Contact
  contact:
    enable: true
    content: My inbox is always open. Whether you have a question or just want to say hi, Iâ€™ll try my best to get back to you!
    email: apgillock@gmail.com
    btnName: email me!

  footer:
    recentPosts: false
    socialNetworks:
      github: https://github.com/andrewgillock
      linkedin: https://linkedin.com/in/andrewgillock
      #twitter: https://twitter.com
      #instagram: https://instagram.com
      #facebook: https://www.facebook.com/profile.php?id=100010942300038
